AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    ./slack-api-identity-proxy

# More info about Globals: https://slack.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Runtime: nodejs16.x
        Timeout: 15
        Environment:
          Variables:
            SLACK_CLIENT_ID:
              Ref: SlackClientIdParameter
            SLACK_CLIENT_SECRET:
              Ref: SlackClientSecretParameter
            COGNITO_REDIRECT_URI:
              Ref: CognitoRedirectUriParameter
            SLACK_API_URL:
              Ref: SlackUrlParameter
            SLACK_LOGIN_URL:
              Ref: SlackLoginUrlParameter

Parameters:
  SlackClientIdParameter:
    Type: String
  SlackClientSecretParameter:
    Type: String
  CognitoRedirectUriParameter:
    Type: String
  SlackUrlParameter:
    Type: String
    Default: "https://slack.com"
    MinLength: 1
  SlackLoginUrlParameter:
    Type: String
    Default: "https://slack.com"
    MinLength: 1

Resources:
  OpenIdDiscovery:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: openIdConfiguration.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /.well-known/openid-configuration
            Method: get
  Authorize:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: authorize.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /authorize
            Method: get
  Token:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: token.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /token
            Method: get
        PostResource:
          Type: Api
          Properties:
            Path: /token
            Method: post
  UserInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: userinfo.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /userinfo
            Method: get
        PostResource:
          Type: Api
          Properties:
            Path: /userinfo
            Method: post
  Jwks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist-lambda
      Handler: jwks.handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /.well-known/jwks.json
            Method: get

Outputs:
    SlackShimIssuer:
      Description: "Slack OpenID Shim Issuer"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
